### ISSUE TITLE
After 1.0.1, `null` is added at the end of all generated classes

### ISSUE THREAD

**Issue by ryangardner** [IgorPerikov/hollow-maven-plugin#14]
I think this is related to #13 - 

 if I use version 1.0.1 and either don't specify any `classPostfix` or specify a class postfix of `<classPostfix></classPostfix>` it adds `null` as a class postfix on everything

What's the proper way to use this _without_ a class postfix specified?

**Comment by IgorPerikov** [comment]
Honestly, I have no idea yet, but I'll take a look
